### ISSUE TITLE
GA senators data issue

### ISSUE THREAD

**Issue by zilinskyjan** [CivilServiceUSA/us-senate#19]
FYI: Johnny Isakson's [row](https://github.com/CivilServiceUSA/us-senate/blob/master/us-senate/data/us-senate.csv) includes social media handles for Kelly Loeffler.

**Comment by manifestinteractive** [comment]
@zilinskyjan This will be resolved in an update that will go out on after new GA Senators are finalized ( around the 20th of this month I believe )

**Comment by rsnbrgr** [comment]
Neither of Georgia's senators yet appear in the data files?

**Comment by manifestinteractive** [comment]
Updating to add missing Georgia Senators & Kamala's CA replacement.

**Comment by manifestinteractive** [comment]
This missing information is now also pushed to the API and website.
