### ISSUE TITLE
Issue: Direct linking to Senators Email Page

### ISSUE THREAD

**Issue by TicoGitHubII** [CivilServiceUSA/us-senate#2]
#### Overview:

Adding a direct email to the site/Senator Profile/Icon may increase  the communication to senators activity of non technical or web savvy users 

Github Newbie

**Comment by manifestinteractive** [comment]
@izzomatik unfortunately, most of these elected officials on the state and federal level do not have public facing emails addresses ( that I have been able to reliably locate anyway ).  Pretty much all they have is a Contact Page where you can send someone to contact them.  Many of these are even protected by asking you what your ZipCode is so they can make sure you are contacting YOUR elected official, and not just getting emails from people they do not represent.
