### ISSUE TITLE
Senator updates

### ISSUE THREAD

**Issue by jeffmcwhirter** [CivilServiceUSA/us-senate#8]
Hi,
A coupleof updates - 
Kevin Cramer is male
John Barrasso is probably not a lesbian

Thanks for the data!

**Comment by jeffmcwhirter** [comment]
Here is an interactive visualization I made of your data -
https://geodesystems.com/repository/entry/show?entryid=4688aa9e-8176-4073-8755-13b6bc9cccf2

**Comment by nickoneill** [comment]
Thanks @jeffmcwhirter! I made these updates in #9
